version: '3'

services:
  selenium-server:
    image: selenium/standalone-chrome
    container_name: selenium-server
    ports:
     - "4444:4444"
    networks:
     - mynetwork 
  moda-api:
    build: ./moda-api
    image: jongwon990806/moda-api:latest
    depends_on:
      - selenium-server
    container_name: moda-api
    ports:
      - "8080:8080"  
    env_file:
      - ./moda-api/.env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
  
