version: '3'

services:
  moda-api:
    build: ./moda-api
    image: jongwon990806/moda-api:latest
    container_name: moda-api
    ports:
      - "8080:8080"
    env_file:
      - ./moda-api/.env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
