version: '3'

services:
  moda-api:
    build: ./moda-api
    image: jongwon990806/moda-api:latest
    container_name: moda-api
    ports:
      - "8080:8080"
   environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      LILYS_API_URL: ${LILYS_API_URL}
      LILYS_API_KEY: ${LILYS_API_KEY}
      PYTHON_AI_API_URL: ${PYTHON_AI_API_URL}
      DB_URL: ${DB_URL}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ELASTIC_SEARCH_URIS: ${ELASTIC_SEARCH_URIS}
      ELASTIC_SEARCH_USERNAME: ${ELASTIC_SEARCH_USERNAME}
      ELASTIC_SEARCH_PASSWORD: ${ELASTIC_SEARCH_PASSWORD}
      FCM_CREDENTIALS_PATH: ${FCM_CREDENTIALS_PATH}