services:
  nlp:
    image: moda-nlp
    container_name: moda-nlp
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4